version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: prime-video-notice-db
    volumes:
      - prime-video-notice-db-store:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Tokyo
    ports:
      - 23306:3306

# データを永続化させるため
volumes:
  prime-video-notice-db-store:
